# Generated by Django 4.2.4 on 2023-09-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_package_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время доставки'),
        ),
    ]
