# Generated by Django 4.2.4 on 2023-09-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_productcardimage_product_cards_and_more'),
        ('orders', '0004_order_delivery_date_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productoffercard', verbose_name='Карточка товара'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер'),
        ),
    ]
