# Generated by Django 4.2.5 on 2023-10-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='building',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='housing',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дом'),
        ),
    ]
