# Generated by Django 4.2.5 on 2023-10-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_building_alter_order_housing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='retail_crm_log',
            field=models.TextField(blank=True, null=True, verbose_name='Лог RetailCRM'),
        ),
    ]
