# Generated by Django 4.2.5 on 2023-10-26 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0012_remove_deliverytype_retailcrm_id_and_more'),
        ('orders', '0008_order_retail_crm_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='self_delivery_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='handbooks.selfdeliverypoint', verbose_name='Собственный пункт самовывоза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='handbooks.deliverylistpoint', verbose_name='Пункт доставки'),
        ),
    ]
