# Generated by Django 4.2.6 on 2023-10-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_self_delivery_point_alter_order_delivery_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_payment_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.SmallIntegerField(choices=[(-1, 'Не оплачено'), (0, 'Ожидает подтверждения'), (1, 'Оплачено')], default=-1, verbose_name='Статус оплаты'),
        ),
    ]
