# Generated by Django 4.2.6 on 2023-11-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_last_payment_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='utm_campaign',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UTM Campaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_content',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UTM Content'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_medium',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_placement',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UTM Placement'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UTM Source'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_term',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UTM Term'),
        ),
    ]
