# Generated by Django 4.2.6 on 2024-11-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_utm_campaign_order_utm_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yookassa_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='ID в ЮKassa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.SmallIntegerField(choices=[(-1, 'Не оплачено'), (0, 'Ожидает подтверждения'), (1, 'Оплачено'), (2, 'Оплачено частично (Подели)')], default=-1, verbose_name='Статус оплаты'),
        ),
    ]
