# Generated by Django 4.2.6 on 2024-11-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_utm_campaign_order_utm_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Комиссия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.SmallIntegerField(choices=[(-1, 'Не оплачено'), (0, 'Ожидает подтверждения'), (1, 'Оплачено'), (2, 'Оплачено частично (Подели)')], default=-1, verbose_name='Статус оплаты'),
        ),
    ]
