# Generated by Django 4.2.6 on 2024-11-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_comission_alter_order_payment_status'),
        ('orders', '0012_order_yookassa_id_alter_order_payment_status'),
    ]

    operations = [
    ]
