# Generated by Django 4.2.6 on 2025-03-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_merge_20241126_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Бонусы'),
        ),
    ]
